### ISSUE TITLE
Investigate ASG enhancements to cg_space

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/terraform-cloudgov#52]
## Story

As a ***devops engineer***,
I would like to ***define my space ASG rules via terraform***,
So that I can ***get rid of the set_space_egress.sh script***

## Solution

```[tasklist]
### Tasks
- [x] investigate current status of https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/issues/405
- [x] Utilize [security-group-spaces](https://github.com/cloudfoundry/terraform-provider-cloudfoundry/blob/main/migration-guide/resources/security_group_spaces.md) once provider version after 1.1.0 is released
```

## Acceptance Criteria

- [ ] cg_space module can accept a list of ASG names to apply

**Comment by rahearn** [comment]
[1.2.0](https://github.com/cloudfoundry/terraform-provider-cloudfoundry/milestone/1) possibly out in mid january?

**Comment by rahearn** [comment]
> [1.2.0](https://github.com/cloudfoundry/terraform-provider-cloudfoundry/milestone/1) possibly out in mid january?

out on Jan 15, on the dot
